/**
 * Motion Design Tokens
 *
 * Central configuration for all timing, easing, and rhythm values.
 * Generated by the design system matcher during pre-production.
 * Replace these values with the matched design system output.
 */

export const motionTokens = {
  duration: {
    fast: { scene: 90, element: 8, transition: 10, stagger: 2 },
    normal: { scene: 180, element: 15, transition: 20, stagger: 4 },
    slow: { scene: 300, element: 30, transition: 36, stagger: 6 },
  },

  easing: {
    default: "power2.out",
    entrance: "power2.out",
    exit: "power2.in",
    emphasis: "elastic.out(1, 0.3)",
    bounce: "bounce.out",
    smooth: "power3.inOut",
    dramatic: "expo.out",
    linear: "none",
  },

  spring: {
    gentle: { damping: 20, stiffness: 100, mass: 0.5 },
    default: { damping: 15, stiffness: 200, mass: 0.5 },
    bouncy: { damping: 8, stiffness: 200, mass: 0.8 },
    stiff: { damping: 25, stiffness: 300, mass: 0.3 },
  },
} as const;

export interface VideoPalette {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  text: string;
  textSecondary: string;
}

export const defaultPalette: VideoPalette = {
  primary: "#6366F1",
  secondary: "#818CF8",
  accent: "#22D3EE",
  background: "#0F172A",
  surface: "#1E293B",
  text: "#F8FAFC",
  textSecondary: "#94A3B8",
};

export interface VideoTypography {
  heading: string;
  body: string;
  mono: string;
  sizes: {
    title: number;
    subtitle: number;
    body: number;
    caption: number;
  };
  weights: {
    title: number;
    subtitle: number;
    body: number;
    caption: number;
  };
}

export const defaultTypography: VideoTypography = {
  heading: "Inter",
  body: "Inter",
  mono: "JetBrains Mono",
  sizes: { title: 64, subtitle: 40, body: 28, caption: 20 },
  weights: { title: 700, subtitle: 600, body: 400, caption: 400 },
};

export const outputPresets = {
  "douyin": { width: 1080, height: 1920, fps: 30 },
  "tiktok": { width: 1080, height: 1920, fps: 30 },
  "reels": { width: 1080, height: 1920, fps: 30 },
  "youtube": { width: 1920, height: 1080, fps: 30 },
  "bilibili": { width: 1920, height: 1080, fps: 30 },
  "instagram": { width: 1080, height: 1080, fps: 30 },
  "xiaohongshu": { width: 1080, height: 1440, fps: 30 },
} as const;
